TrackerManager = {
 title = 'Issue Tracker Manager'
}

-- Returns the name of the app associated with tracker (Jira, GitHub, etc)
function TrackerManager:GetTrackerApp(name)
  local jsonfile = symini.info.configdir..'\\Tracker\\'..name..'.json'
  local j = ctk.json.object:new()
  local app = ''
  j:loadfromfile(jsonfile)
  app = j['tracker.defaultapp']
  j:release()
  return app
end

function TrackerManager:EditTrackerPreferences(name, app)
  local jsonfile = symini.info.configdir..'\\Tracker\\'..name..'.json'
  local slp = ctk.string.loop:new()
  local hs = symini.hybrid:new()
  hs:start()
  slp:load(hs.options)
  while slp:parsing() do
    prefs.regdefault(slp.current,hs:prefs_getdefault(slp.current))
  end
  local t = {}
  t.html = SyHybrid:getfile('hybrid/prefs_tracker/prefs_'..app:lower()..'.html')
  t.id = 'syhunttrackerprefs'
  t.options = hs.options
  t.jsonfile = jsonfile
  Sandcat.Preferences:EditCustomFile(t)
  hs:release()
  slp:release()
end

function TrackerManager:SubmitIssue_FromVulnFileList(tracker, filenamelist)
  local app = self:GetTrackerApp(tracker)
  local script = SyHybrid:getfile('hybrid/trackman/sendtask.lua')
  local j = ctk.json.object:new()
  j.tracker = tracker
  j.app = app
  j.filenamelist = filenamelist
  local tid = tab:runtask(script,tostring(j))
  j:release()
end

function TrackerManager:SubmitIssue_FromVulnFile(tracker, filename)
  local trackerapp = self:GetTrackerApp(tracker)
  local issue = {}
  local ses = symini.session:new()
  issue = ses:gettrackerissue(filename, trackerapp)
  issue.tracker = tracker
  ses:release()
  self:SubmitIssue(issue)
end

function TrackerManager:SubmitIssue(issue)
  local hs = symini.hybrid:new()
  hs:start()
  local res = hs:tracker_sendissue(issue)
  if res.alreadysent == true then
    app.showmessage('Already sent!')
  else
    if res.success == true then
      app.showmessage('Success! '..res.errormsg)
    else
      app.showmessage('Failed! '..res.errormsg)
    end
  end
  hs:release()
end

function TrackerManager:TestIssueTracker(name)
  local issue = {}
  issue.tracker = name
  issue.summary = 'Syhunt Test Issue'
  issue.description = 'This is a test issue generated by Syhunt.'
  self:SubmitIssue(issue)
end

function TrackerManager:AddIssueTracker(appname)
  if SyHybridUser:IsOptionAvailable(true) == true then
    local name = app.showinputdialog('Enter name:','')
    name = ctk.file.cleanname(name)
    if name ~= '' then
      local item  = {}
      item.name = name
      item.url = appname
      HistView:AddURLLogItem(item, 'Issue Trackers')
    end
    self:ViewIssueTrackers(false)
  end
end

function TrackerManager:DoIssueTrackerAction(action, itemid)
  local item = HistView:GetURLLogItem(itemid, 'Issue Trackers')
  if item ~= nil then
    if action == 'editprefs' then
      self:EditTrackerPreferences(item.name, item.url)
      self:ViewIssueTrackers(false)
    end
    if action == 'test' then
      self:TestIssueTracker(item.name)
    end
  end
end

function TrackerManager:GetIssueTrackerList()
  HistView = HistView or Sandcat:require('histview')  
  return HistView:GetURLLogItemNames('Issue Trackers')
end

function TrackerManager:ViewIssueTrackers(newtab)
 local t = {}
 t.newtab = newtab
 t.toolbar = 'SyHybrid.scx#hybrid/trackman/toolbar.html'
 t.histname = 'Issue Trackers'
 t.tabicon = 'url(SyHybrid.scx#images\\16\\bug_alt.png);'
 t.html = Sandcat:getfile('histview_list.html')
 t.style = [[
  ]]
 t.menu = [[
  <li onclick="TrackerManager:DoIssueTrackerAction('editprefs','%i')">Edit Tracker Preferences...</li>
  <hr/>
  <li onclick="TrackerManager:DoIssueTrackerAction('test','%i')">Submit Test Issue</li>
  <hr/>
  <li onclick="HistView:DeleteURLLogItem('%i','Issue Trackers')">Delete</li>
  ]]  
 HistView = HistView or Sandcat:require('histview')  
 HistView:ViewURLLogFile(t)
end